# Generated by Django 4.0.5 on 2022-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_attendancerange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Prelim Exam', 'Prelim Exam'), ('Midterm Exam', 'Midterm Exam'), ('EndTerm Exam', 'EndTerm Exam'), ('Short Quiz', 'Short Quiz'), ('Long Quiz', 'Long Quiz'), ('Weekly Test', 'Weekly Test')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Prelim Exam', 'Prelim Exam'), ('Midterm Exam', 'Midterm Exam'), ('EndTerm Exam', 'EndTerm Exam'), ('Short Quiz', 'Short Quiz'), ('Long Quiz', 'Long Quiz'), ('Weekly Test', 'Weekly Test')], default='Internal test 1', max_length=50),
        ),
    ]
